sudo: required

services:
  - docker

matrix:
  include:
    - language: python
      python:
        - 3.7
      dist: xenial
      script:
        - cd backend
        - pytest

    - language: node_js
      node_js:
        - node
      script:
        - cd frontend
        - yarn run test
      cache:
        yarn: true
        directories:
          - node_modules
