version: '3.7'
services:

  backend:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:10.4
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: always

volumes:
  db_data:
