version: '3.4'
services:

  api:
    build: .
    command: python run.py
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
